export interface FitnessTest {
  weight: number,
  body_fat: number,
  chest: number,
  right_arm_contr: number,
  left_arm_contr: number,
  hip: number,
  right_arm_relax: number,
  left_arm_relax: number,
  abdomen: number,
  waist: number,
  right_forearm: number,
  left_forearm: number,
  right_thigh: number,
  left_thigh: number,
  scapular: number,
  right_calf: number,
  left_calf: number,
  observations: string,
  user_id: number
}

export interface GetFitnessTest {
  weight: number,
  body_fat: number,
  chest: number,
  right_arm_contr: number,
  left_arm_contr: number,
  hip: number,
  right_arm_relax: number,
  left_arm_relax: number,
  abdomen: number,
  waist: number,
  right_forearm: number,
  left_forearm: number,
  right_thigh: number,
  left_thigh: number,
  scapular: number,
  right_calf: number,
  left_calf: number,
  observations: string,
  id: number,
  date: string
}
